#!/usr/bin/env node
if (process.platform !== 'win32') {
  const omelette = require('omelette')

  const commands = require('./binaries')

  for (const command of commands) {
    omelette(command).setupShellInitFile()
  }
}
