#!/usr/bin/env node
if (process.platform !== 'win32') {
  const { join } = require('path')
  const { HOME, SHELL } = process.env

  const commands = require('./binaries')

  const shellFile = SHELL.match(/bash/) ? join(HOME, '.bash_profile')
    : SHELL.match(/zsh/) ? join(HOME, '.zshrc')
    : SHELL.match(/fish/) ? join(HOME, '.config/fish/config.fish')
    : null

  const { readFileSync, writeFileSync, existsSync } = require('fs')

  if (shellFile && existsSync(shellFile)) {
    let shellFileContents = readFileSync(shellFile, 'utf8')

    // From: https://stackoverflow.com/a/6969486/2048874
    const escape = str => str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&")

    for (const command of commands) {
      const block = `
# begin ${command} completion
. <(${command} --completion)
# end ${command} completion
`

      shellFileContents = shellFileContents.replace(new RegExp(escape(block), 'g'), '')
    }

    writeFileSync(shellFile, shellFileContents)
  }
}
